services:
  - type: web
    name: smart-event-planner
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: OPENWEATHER_API_KEY
        value: <your_openweather_api_key>
      - key: SUPABASE_URL
        value: <your_supabase_url>
      - key: SUPABASE_ANON_KEY
        value: <your_supabase_anon_key>
    autoDeploy: true 